---
name: Lint

on:
  push:

jobs:
  tflint:
    name: tflint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: Run TFLint
        run: tflint --recursive
